version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:3000/api/health"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
